### ISSUE TITLE
Getting security alerts while using this action for enterprise project

### ISSUE THREAD

**Issue by manoj27730** [matlab-actions/run-tests#31]
Hi Team,

I need this actions to be used by my project and since it's not allowed by default our enterprise GitHub Team need to review and add it for our project. Our GitHub Team has found alert and mentioned below point.

**<img width="532" alt="Alert" src="https://user-images.githubusercontent.com/24359931/199657419-da2050d5-22fa-4e02-aad0-8fbabc8fa343.PNG">**

Can you please look into it and help.

**Comment by manoj27730** [comment]
**"The actions requested are available on our github instance but we are seeing dependabot alerts. Since those repo have vulnerabilities, we won’t be able to make it public. Look like it’s patched on the master but they haven’t release it. Please file issue with the actions owner to release patched version. After that, we can make it available for your team to use."**

**Comment by manoj27730** [comment]
![Uploading Capture.PNG…]()

**Comment by manoj27730** [comment]
<img width="550" alt="Capture" src="https://user-images.githubusercontent.com/24359931/199657957-f93f4c8d-4f16-4395-a704-ec862e9fe544.PNG">

**Comment by davidbuzinski** [comment]
Hi @manoj27730 thanks for bringing this to our attention. We have bumped the mentioned dependencies in the new release v1.3.2.

Thanks,
David
